# Generated by Django 2.1.7 on 2019-03-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Query',
        ),
    ]
